name: feature
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_model:
    path: ./../core_model
  lib_use_case:
    path: ./../lib_use_case
  get_it: 7.2.0
  flutter_bloc: 8.1.1
  freezed_annotation: ^2.2.0
  go_router: 6.0.0
  cached_network_image: 3.2.2
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.2.1

flutter:
