name: readwise_client

sdkPath: .fvm/flutter_sdk

ide:
  intellij: false

packages:
  - app/**
  - core_model/**
  - core_data/**
  - core_database/**
  - core_network/**
  - lib_use_case/**
  - feature_book_list/**
  - feature_settings/**
  - '*'