name: readwise_client

sdkPath: .fvm/flutter_sdk

ide:
  intellij: true

packages:
  - app/**
  - core_model/**
  - core_data/**
  - core_database/**
  - core_network/**
  - lib_di/**
  - lib_use_case/**
  - feature/**
  - '*'

scripts:
  build_runner:build:
    run: |
      melos exec fvm flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on:
        - build_runner
    description: |
      Code generation.
  apply_preset_versions:
    run: |
      python3 script/versions.py && melos exec fvm flutter pub get
    description:
      Make dependency versions identical across packages.